version: '3.8'

services:
  static-service-server:
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
        - NODE_VERSION=${NODE_VERSION}
    ports:
      - ${PORT}:${PORT}
    restart: on-failure
    environment:
      - PORT=${PORT}