name: Create Release
run-name: Release ${{ github.run_number }} creation was triggered by ${{ github.actor }} on ${{ github.event_name }} event

env:
  RELEASE_VERSION: ${{ github.run_number }}

on:
  workflow_dispatch:

jobs:
  linter-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

  tests-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

  create-release-branch:
    runs-on: ubuntu-latest
    needs:
      - linter-checks
      - tests-checks

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Configure Git
        run: |
          git config --global user.name "Shri-Deploy-Bot"
          git config --global user.email "igorbarbashov@yandex.ru"

      - name: Set Release branch name
        id: set_branch_name
        run: echo "BRANCH_NAME=releases/${{ env.RELEASE_VERSION }}" >> $GITHUB_ENV

      - name: Create new branch
        run: |
          git checkout main
          git pull origin main
          git checkout -b ${{ env.BRANCH_NAME }}
          git push origin ${{ env.BRANCH_NAME }}

      - name: Echo job name
        run: echo "Create Release branch ${{ env.BRANCH_NAME }}"
